### ISSUE TITLE
[Discussão] Melhorar mensagem de erro ao fazer requisição

### ISSUE THREAD

**Issue by bartier** [felipemfp/sinonimos#39]
## 🔱 Issue subject

- [ ] 👽 **Bug**
- [X] 🔥 **New feature proposal**
- [ ] 💭 **Idea/need**
- [ ] ❓ **Other**

### 🔥 **New feature proposal**

Melhorar mensagem de tratamento quando a chamada a API não é realizada com sucesso (exemplos: internet off ou resposta pode ser de server error visto alguma indisponibilidade temporária).

Mensagem atual:
```
user@pc:~$ sinonimos teste
Buscando sinônimos para "teste":

... falhou (Get https://www.sinonimos.com.br/teste/: dial tcp: lookup www.sinonimos.com.br on 127.0.0.53:53: server misbehaving)
```

#### New feature
Substituir **falhou (Get https://www.sinonimos.com.br/teste/: dial tcp: lookup www.sinonimos.com.br on 127.0.0.53:53: server misbehaving)** por algo mais expressivo/interessante.

Basicamente é isso... Acham válido essa feature? Caso sim, seria legal discutir o tipo de mensagem a ser retornada, caso contrário vida que segue haha... 

:)

## ➕ More
If you need help or have doubts, ping team members (@felipemfp)
Otherwise, you can write here anything that is not covered above.

**Comment by felipemfp** [comment]
Ter melhores mensagens de error com certeza é uma feature válida.

Temos que tratar os errors da [http.Get](https://golang.org/pkg/net/http/#Client.Get):

> An error is returned if the Client's CheckRedirect function fails or if there was an HTTP protocol error. A non-2xx response doesn't cause an error. Any returned error will be of type *url.Error. The url.Error value's Timeout method will report true if request timed out or was canceled.

Outro ponto que podemos tratar é o [html.Parse](https://github.com/felipemfp/sinonimos-cli/blob/master/src/sinonimos/main.go#L71). Nesse caso, só podemos assumir que a resposta não tá no encoding correto.

Estou com pouco tempo ultimamente, então adoraria aceitar um PR com essa contribuição. :+1:
