### ISSUE TITLE
[Instalação] Algum passo a mais é necessário?

### ISSUE THREAD

**Issue by bartier** [felipemfp/sinonimos#42]
🔱 Issue subject

- [X] 👽 **Bug**
- [ ] 🔥 **New feature proposal**
- [ ] 💭 **Idea/need**
- [ ] ❓ **Other**

### 👽 **Bug**

1. What did you do?

Após uma formatação, instalei o Go versão 1.13 e executei o comando abaixo conforme instruções do README:

`go get github.com/felipemfp/sinonimos/...`

![image](https://user-images.githubusercontent.com/18057391/64492791-85779700-d24e-11e9-9063-9b0222b4fff5.png)

2. What did you expect to see?

Instalação normal. `sinonimos --help` funcional

3. What did you see instead?

O erro da imagem acima:
`.asdf/installs/golang/1.13/packages/src/github.com/felipemfp/sinonimos/cmd/sinonimos/main.go:65:26: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
`
  
Como medida paliativa utilizei a maneira antiga de instalação:

`sudo curl -L "https://github.com/felipemfp/sinonimos-cli/releases/download/v0.4.0/sinonimos" -o /usr/local/bin/sinonimos`

Por gentileza, poderiam auxiliar?

@felipemfp Assim que tiver tempo pretendo resolver as issues #39 e #41. Estou a disposição qualquer coisa, no entanto realmente o tempo está limitado no momento.

**Comment by felipemfp** [comment]
Isso acontece porque o [`aurora`](https://github.com/logrusorgru/aurora) não segue o [semver](https://semver.org/).

Acabei substituindo algumas dependências que não tinham release ou não seguiam o semver (#43).

Lancei [a nova versão](https://github.com/felipemfp/sinonimos/releases/tag/v0.7.0) e deve funcionar de boas agora.
